host: chat.johannes-jahn.com
volumeBasePath: /home/nacho/chat-api
images:
  backend:
    name: johannesjahn/chat-api
    version: 2.1.96
  frontend:
    name: johannesjahn/nacho-chat
    version: 1.6.54
secrets:
  DB_USER: 'chat'
  DB_PASS: 'chat2'
  DB: 'chat'
  JWT_SECRET: 'JWT_SECRET'
  SALT: '123456789ABCDEFG'
